name: Chromatic (staging)
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: yarn install --frozen-lockfile
      - uses: chromaui/action-canary@v1
        with:
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
        env:
          CHROMATIC_PROJECT_TOKEN: 253df72b53d2
          CHROMATIC_INDEX_URL: https://index.staging-chromatic.com
      - uses: actions/upload-artifact@v2
        with:
          name: chromatic-diagnostics
          path: chromatic-diagnostics.json
