name: Smoke test via npm
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v1
      - name: install
        run: npm install && git status --porcelain
      - name: prep package
        run: ./scripts/rename.js storybook-chromatic
        run: npm run bundle:bin
      - name: run chromatic
        run: npm run chromatic -- --build-script-name build-test-storybook --exit-zero-on-changes
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: 47c20821d2c2
