name: Smoke test via yarn classic
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn set version 1.x.x
      - name: run chromatic
        run: npx -p . chromatic --build-script-name build-test-storybook --exit-zero-on-changes
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: 47c20821d2c2
