name: Smoke test via action
on: push

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn build
      - run: yarn build-storybook
      - uses: ./
        with:
          storybookBuildDir: storybook-static
          autoAcceptChanges: true
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: 47c20821d2c2
