name: Smoke test via npx
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v1
      - name: install
        run: yarn && git status --porcelain
      - name: prep package
        run: ./scripts/rename.js storybook-chromatic
      - name: run chromatic
        run: npx -p . chromatic --auto-accept-changes
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: 47c20821d2c2
