name: Smoke test via yarn canary
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v1
      - name: switch to yarn berry
        run: yarn set version berry
      - name: switch to yarn canary
        run: yarn set version canary
      - name: install
        run: rm yarn.lock && yarn install
      - name: run chromatic
        run: yarn chromatic --build-script-name build-test-storybook --exit-zero-on-changes
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: 47c20821d2c2
